name: Build Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o dnsping dnsping.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o dnsping.exe dnsping.go

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o dnsping-macos dnsping.go

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dnsping
            dnsping.exe
            dnsping-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
